---

- name: Redis installation
  apt:
    name: redis-server
    state: present
    update_cache: true

- name: Redis service activation
  service:
    name: redis-server
    state: started
    enabled: yes

- name: Open port for redis
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 6379
    jump: ACCEPT